version: "3.8"

services:
  shairport-sync:
    image: mikebrady/shairport-sync
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd"
    volumes:
      - ./shairport-sync.conf:/etc/shairport-sync.conf
    logging:
      options:
        max-size: "200k"
        max-file: "10"
